const employeesData = [
  {
    "id": ".0001",
    "nome": "Brenda Melissa de Jesus Costa",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 397.13,
    "inss": 179.13,
    "fgts": 179.76,
    "transporte": 316.0,
    "adiantamento": 0,
    "total": 2384.0
  },
  {
    "id": ".0002",
    "nome": "Ester do Nascimento Fialho",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 352.41,
    "inss": 175.41,
    "fgts": 176.15,
    "transporte": 270.0,
    "adiantamento": 0,
    "total": 2297.0
  },
  {
    "id": ".0003",
    "nome": "Evandro José de Souza Alves",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 2800.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 2800.0
  },
  {
    "id": ".0004",
    "nome": "Geraldo Rosa de Jesus",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 490.29,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 37.66,
    "fgts": 39.2,
    "transporte": 0,
    "adiantamento": 158.63,
    "total": 294.0
  },
  {
    "id": ".0005",
    "nome": "Gleidson Gomes Ferreira",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 740.58,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 46.24,
    "fgts": 49.33,
    "transporte": 482.0,
    "adiantamento": 0,
    "total": 1053.0
  },
  {
    "id": ".0006",
    "nome": "Jairo da Silva",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 346.39,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1654.5
  },
  {
    "id": ".0007",
    "nome": "Jeferson Gomes da Silva",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 51.06,
    "transporte": 0,
    "adiantamento": 0,
    "total": 27.34
  },
  {
    "id": ".0008",
    "nome": "Jennifer Oliveira Santos",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 123.34,
    "insalubridade": 0,
    "hora_extra": 130.0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 271.93
  },
  {
    "id": ".0009",
    "nome": "José Geraldo Gonçalves de Oliveira",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.41,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 143.41,
    "fgts": 148.0,
    "transporte": 316.0,
    "adiantamento": 0,
    "total": 2023.0
  },
  {
    "id": ".0010",
    "nome": "Luis Fernando Boy",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 140.96,
    "inss": 154.96,
    "fgts": 159.22,
    "transporte": 385.6,
    "adiantamento": 0,
    "total": 1974.93
  },
  {
    "id": ".0011",
    "nome": "Marcos Antônio Cardoso da Silva",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 2100.0,
    "insalubridade": 0,
    "hora_extra": 57.22,
    "inss": 158.25,
    "fgts": 161.35,
    "transporte": 241.0,
    "adiantamento": 532.97,
    "total": 867.0
  },
  {
    "id": ".0012",
    "nome": "Maycon Henrique de Paula Dias",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 198.81,
    "transporte": 0,
    "adiantamento": 0,
    "total": 481.08
  },
  {
    "id": ".0013",
    "nome": "Michele Maria Rodrigues",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 387.39,
    "inss": 176.25,
    "fgts": 178.28,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3989.0
  },
  {
    "id": ".0014",
    "nome": "Pedro Moura de Castro",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 161.02,
    "inss": 157.02,
    "fgts": 160.83,
    "transporte": 385.6,
    "adiantamento": 0,
    "total": 1992.93
  },
  {
    "id": ".0015",
    "nome": "Raquel Gomes Silva",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 184.77,
    "inss": 158.77,
    "fgts": 162.74,
    "transporte": 270.0,
    "adiantamento": 0,
    "total": 2146.0
  },
  {
    "id": ".0016",
    "nome": "Roseli Gomes",
    "cargo": "Costureira",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1900.0,
    "insalubridade": 0,
    "hora_extra": 41.75,
    "inss": 146.92,
    "fgts": 152.22,
    "transporte": 148.5,
    "adiantamento": 0,
    "total": 1334.5
  },
  {
    "id": ".0017",
    "nome": "Felipe Furtado Padilha Madeira",
    "cargo": "Projetista",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 4000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 4000.0
  },
  {
    "id": ".0018",
    "nome": "Matheus Magalhães",
    "cargo": "Advogado",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 1600.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1600.0
  },
  {
    "id": ".0019",
    "nome": "Keli (Empregada BH)",
    "cargo": "Limpeza",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 2500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 300.0,
    "total": 2200.0
  },
  {
    "id": ".0020",
    "nome": "Dayane Rodrigues Morais",
    "cargo": "Limpeza",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 2000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 691.2,
    "adiantamento": 0,
    "total": 2691.2
  },
  {
    "id": ".0021",
    "nome": "Washington Guilherme de Jesus",
    "cargo": "Marcineiro",
    "empresa": "Just Smile",
    "mes": "Janeiro",
    "salario_base": 3500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3500.0
  },
  {
    "id": ".0001",
    "nome": "Alessandro Pereira",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 2100.0,
    "insalubridade": 100.0,
    "hora_extra": 0,
    "inss": 168.61,
    "fgts": 171.49,
    "transporte": 0,
    "adiantamento": 0,
    "total": 2075.0
  },
  {
    "id": ".0002",
    "nome": "Andrew Melo de Oliveira",
    "cargo": "Projetista",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 2700.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 218.0,
    "fgts": 216.0,
    "transporte": 300.0,
    "adiantamento": 0,
    "total": 2782.0
  },
  {
    "id": ".0003",
    "nome": "Arthur Vidatti Rodrigues",
    "cargo": "Projetista",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 2700.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 218.0,
    "fgts": 216.0,
    "transporte": 250.0,
    "adiantamento": 0,
    "total": 2732.0
  },
  {
    "id": ".0004",
    "nome": "Celma Campos Amaral",
    "cargo": "Coordenador",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 4000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 308.0,
    "adiantamento": 0,
    "total": 5276.0
  },
  {
    "id": ".0005",
    "nome": "Cleber David Simplicio",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 3000.81,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 327.91,
    "fgts": 291.87,
    "transporte": 366.7,
    "adiantamento": 0,
    "total": 2948.7
  },
  {
    "id": ".0006",
    "nome": "Cristiano Samuel Braz",
    "cargo": "Pintor",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 594.6,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 389.0,
    "fgts": 333.52,
    "transporte": 424.5,
    "adiantamento": 0,
    "total": 1278.5
  },
  {
    "id": ".0007",
    "nome": "Eliseu da Silva Santos",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 2100.0,
    "insalubridade": 100.0,
    "hora_extra": 0,
    "inss": 208.61,
    "fgts": 206.18,
    "transporte": 340.1,
    "adiantamento": 0,
    "total": 2809.1
  },
  {
    "id": ".0008",
    "nome": "Flavia Santos Moreira",
    "cargo": "RH",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 4500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 350.0,
    "adiantamento": 0,
    "total": 4850.0
  },
  {
    "id": ".0009",
    "nome": "Giovanni Pereira Almeida",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 1099.53,
    "transporte": 0,
    "adiantamento": 0,
    "total": 2556.01
  },
  {
    "id": ".0010",
    "nome": "Giselle Castro de Oliveira",
    "cargo": "RH",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 2500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 5833.33
  },
  {
    "id": ".0011",
    "nome": "Guilherme Santiago de Jesus Costa",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 175.16,
    "fgts": 176.28,
    "transporte": 312.0,
    "adiantamento": 0,
    "total": 2341.0
  },
  {
    "id": ".0012",
    "nome": "Jaci Jorge Pacheco",
    "cargo": "Pintor",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 749.2,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 485.6,
    "fgts": 390.91,
    "transporte": 268.5,
    "adiantamento": 0,
    "total": 1080.5
  },
  {
    "id": ".0013",
    "nome": "Janaina Ferreira de Oliveira",
    "cargo": "Serviços Gerais",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 1621.0,
    "insalubridade": 324.2,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1945.2
  },
  {
    "id": ".0014",
    "nome": "Jaqueline Pereira dos Santos",
    "cargo": "Serviços Gerais",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 0
  },
  {
    "id": ".0015",
    "nome": "Jose Antero Fernandes dos Santos",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 4000.0,
    "insalubridade": 1101.4,
    "hora_extra": 0,
    "inss": 453.4,
    "fgts": 371.87,
    "transporte": 300.0,
    "adiantamento": 0,
    "total": 6282.0
  },
  {
    "id": ".0016",
    "nome": "Julio Cezar Martins",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 3000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 0
  },
  {
    "id": ".0017",
    "nome": "Lucas da Silva",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 1053.82,
    "transporte": 0,
    "adiantamento": 0,
    "total": 2488.9
  },
  {
    "id": ".0018",
    "nome": "Marcia Aparecida Soares Faria",
    "cargo": "Coordenador",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 3000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 156.0,
    "fgts": 161.0,
    "transporte": 304.0,
    "adiantamento": 0,
    "total": 3246.0
  },
  {
    "id": ".0019",
    "nome": "Matheus Marcus Costa e Silva",
    "cargo": "Pintor",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 588.4,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 391.8,
    "fgts": 334.69,
    "transporte": 268.5,
    "adiantamento": 0,
    "total": 1113.5
  },
  {
    "id": ".0020",
    "nome": "Newton Alves de Barros Filho",
    "cargo": "Projetista",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 3000.38,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 249.38,
    "fgts": 240.0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 5796.0
  },
  {
    "id": ".0021",
    "nome": "Paulo Henrique Freitas Gusmão",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 95.82,
    "fgts": 102.2,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1182.0
  },
  {
    "id": ".0022",
    "nome": "Rafael Kevin Fernandes Mattos",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 1850.0,
    "insalubridade": 185.0,
    "hora_extra": 0,
    "inss": 172.6,
    "fgts": 174.09,
    "transporte": 316.0,
    "adiantamento": 0,
    "total": 2505.0
  },
  {
    "id": ".0023",
    "nome": "Ramon Campos",
    "cargo": "Coordenador",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 3500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 4411.0
  },
  {
    "id": ".0024",
    "nome": "Renan Gabriel Ferreira",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 2000.49,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 39.99,
    "fgts": 42.66,
    "transporte": 0,
    "adiantamento": 0,
    "total": 493.0
  },
  {
    "id": ".0025",
    "nome": "Washington da Cruz Ribeiro",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Janeiro",
    "salario_base": 3000.0,
    "insalubridade": 649.22,
    "hora_extra": 0,
    "inss": 327.22,
    "fgts": 291.87,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3322.0
  },
  {
    "id": ".0001",
    "nome": "Brenda Melissa de Jesus Costa",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1850.0,
    "insalubridade": 135.83,
    "hora_extra": 0,
    "inss": 136.88,
    "fgts": 143.29,
    "transporte": 331.8,
    "adiantamento": 0,
    "total": 2121.8
  },
  {
    "id": ".0002",
    "nome": "Ester do Nascimento Fialho",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1850.67,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 142.67,
    "fgts": 148.0,
    "transporte": 297.0,
    "adiantamento": 0,
    "total": 2005.0
  },
  {
    "id": ".0003",
    "nome": "Evandro José de Souza Alves",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 3400.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3400.0
  },
  {
    "id": ".0004",
    "nome": "Geraldo Rosa de Jesus",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 420.76,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 31.5,
    "fgts": 33.6,
    "transporte": 338.8,
    "adiantamento": 236.26,
    "total": 491.8
  },
  {
    "id": ".0005",
    "nome": "Gleidson Gomes Ferreira",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 800.0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 650.0,
    "total": 780.06
  },
  {
    "id": ".0006",
    "nome": "José Geraldo Gonçalves de Oliveira",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1418.4,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 37.4,
    "fgts": 113.46,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1381.0
  },
  {
    "id": ".0007",
    "nome": "Luis Fernando Boy",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 59.72,
    "inss": 146.72,
    "fgts": 152.03,
    "transporte": 506.1,
    "adiantamento": 500.0,
    "total": 1760.1
  },
  {
    "id": ".0008",
    "nome": "Marcos Antônio Cardoso da Silva",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 2100.0,
    "insalubridade": 0,
    "hora_extra": 58.11,
    "inss": 167.88,
    "fgts": 170.84,
    "transporte": 0,
    "adiantamento": 782.97,
    "total": 4025.55
  },
  {
    "id": ".0009",
    "nome": "Michele Maria Rodrigues",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 62.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 195.11,
    "transporte": 0,
    "adiantamento": 0,
    "total": 62.0
  },
  {
    "id": ".0010",
    "nome": "Pedro Moura de Castro",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1850.42,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 141.42,
    "fgts": 147.32,
    "transporte": 506.1,
    "adiantamento": 200.0,
    "total": 2006.1
  },
  {
    "id": ".0011",
    "nome": "Raquel Gomes Silva",
    "cargo": "Aux. de Produção",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1850.6,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 142.6,
    "fgts": 148.0,
    "transporte": 297.0,
    "adiantamento": 0,
    "total": 2005.0
  },
  {
    "id": ".0012",
    "nome": "Roseli Gomes",
    "cargo": "Costureira",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1900.24,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 147.24,
    "fgts": 152.0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 4083.0
  },
  {
    "id": ".0013",
    "nome": "Felipe Furtado Padilha Madeira",
    "cargo": "Projetista",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 4000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 4000.0
  },
  {
    "id": ".0014",
    "nome": "Matheus Magalhães",
    "cargo": "Advogado",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 1600.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1600.0
  },
  {
    "id": ".0015",
    "nome": "Keli (Empregada BH)",
    "cargo": "Limpeza",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 2500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 2500.0
  },
  {
    "id": ".0016",
    "nome": "Dayane Rodrigues Morais",
    "cargo": "Limpeza",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 2000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 748.8,
    "adiantamento": 0,
    "total": 2748.8
  },
  {
    "id": ".0017",
    "nome": "Washington Guilherme de Jesus",
    "cargo": "Marcineiro",
    "empresa": "Just Smile",
    "mes": "Fevereiro",
    "salario_base": 3500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3500.0
  },
  {
    "id": ".0001",
    "nome": "Alessandro Pereira",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 0
  },
  {
    "id": ".0002",
    "nome": "Andrew Melo de Oliveira",
    "cargo": "Projetista",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3000.86,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 244.82,
    "fgts": 237.49,
    "transporte": 300.0,
    "adiantamento": 0,
    "total": 3024.0
  },
  {
    "id": ".0003",
    "nome": "Arthur Vidatti Rodrigues",
    "cargo": "Projetista",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3000.26,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 246.13,
    "fgts": 238.36,
    "transporte": 250.0,
    "adiantamento": 0,
    "total": 2983.0
  },
  {
    "id": ".0004",
    "nome": "Celma Campos Amaral",
    "cargo": "Coordenador",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 4000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 338.8,
    "adiantamento": 0,
    "total": 4338.8
  },
  {
    "id": ".0005",
    "nome": "Cleber David Simplicio",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3000.0,
    "insalubridade": 648.5,
    "hora_extra": 0,
    "inss": 278.39,
    "fgts": 259.87,
    "transporte": 386.0,
    "adiantamento": 0,
    "total": 2616.0
  },
  {
    "id": ".0006",
    "nome": "Cristiano Samuel Braz",
    "cargo": "Pintor",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 2037.08,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 217.37,
    "fgts": 214.83,
    "transporte": 622.6,
    "adiantamento": 0,
    "total": 2427.6
  },
  {
    "id": ".0007",
    "nome": "Eliseu da Silva Santos",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 2100.0,
    "insalubridade": 100.0,
    "hora_extra": 0,
    "inss": 167.35,
    "fgts": 170.37,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1828.0
  },
  {
    "id": ".0008",
    "nome": "Flavia Santos Moreira",
    "cargo": "RH",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 4500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 700.0,
    "adiantamento": 0,
    "total": 5200.0
  },
  {
    "id": ".0010",
    "nome": "Giselle Castro de Oliveira",
    "cargo": "RH",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 166.99,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 250.0,
    "adiantamento": 0,
    "total": 417.0
  },
  {
    "id": ".0011",
    "nome": "Guilherme Santiago de Jesus Costa",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 1850.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 132.69,
    "fgts": 139.57,
    "transporte": 327.6,
    "adiantamento": 0,
    "total": 1939.6
  },
  {
    "id": ".0012",
    "nome": "Jaci Jorge Pacheco",
    "cargo": "Pintor",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 2528.89,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 262.67,
    "fgts": 249.39,
    "transporte": 393.8,
    "adiantamento": 0,
    "total": 2289.8
  },
  {
    "id": ".0013",
    "nome": "Janaina Ferreira de Oliveira",
    "cargo": "Serviços Gerais",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 1621.0,
    "insalubridade": 324.2,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1945.2
  },
  {
    "id": ".0014",
    "nome": "Jaqueline Pereira dos Santos",
    "cargo": "Serviços Gerais",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 0
  },
  {
    "id": ".0015",
    "nome": "Jose Antero Fernandes dos Santos",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 4000.9,
    "insalubridade": 1100.7,
    "hora_extra": 0,
    "inss": 452.3,
    "fgts": 371.87,
    "transporte": 300.0,
    "adiantamento": 0,
    "total": 4949.3
  },
  {
    "id": ".0016",
    "nome": "Julio Augusto de Oliveira Barros",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 1233.4,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1252.0
  },
  {
    "id": ".0017",
    "nome": "Julio Cezar Martins",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3000.78,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 108.63,
    "fgts": 115.87,
    "transporte": 682.0,
    "adiantamento": 0,
    "total": 2022.0
  },
  {
    "id": ".0018",
    "nome": "Luciano Alcantara de Araujo",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 750.0,
    "insalubridade": 162.1,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 150.0,
    "adiantamento": 0,
    "total": 1062.1
  },
  {
    "id": ".0019",
    "nome": "Marcia Aparecida Soares Faria",
    "cargo": "Coordenador",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3000.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 167.0,
    "fgts": 170.24,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3833.0
  },
  {
    "id": ".0020",
    "nome": "Matheus Marcus Costa e Silva",
    "cargo": "Pintor",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 2157.93,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 228.16,
    "fgts": 224.42,
    "transporte": 393.8,
    "adiantamento": 0,
    "total": 2606.8
  },
  {
    "id": ".0021",
    "nome": "Newton Alves de Barros Filho",
    "cargo": "Projetista",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 100.0,
    "insalubridade": 833.48,
    "hora_extra": 0,
    "inss": 360.57,
    "fgts": 314.65,
    "transporte": 0,
    "adiantamento": 0,
    "total": 2165.33
  },
  {
    "id": ".0022",
    "nome": "Paulo Henrique Freitas Gusmão",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 876.62,
    "transporte": 0,
    "adiantamento": 0,
    "total": 1903.51
  },
  {
    "id": ".0023",
    "nome": "Rafael Kevin Fernandes Mattos",
    "cargo": "Serviços Gerais",
    "origem": "LT 100%",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 1850.0,
    "insalubridade": 67.54,
    "hora_extra": 0,
    "inss": 142.77,
    "fgts": 148.53,
    "transporte": 347.6,
    "adiantamento": 0,
    "total": 1697.6
  },
  {
    "id": ".0024",
    "nome": "Ramon Campos",
    "cargo": "Coordenador",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3500.0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 0,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3000.0
  },
  {
    "id": ".0025",
    "nome": "Renan Gabriel Ferreira",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 0,
    "insalubridade": 0,
    "hora_extra": 0,
    "inss": 0,
    "fgts": 427.22,
    "transporte": 0,
    "adiantamento": 0,
    "total": 871.91
  },
  {
    "id": ".0026",
    "nome": "Washington da Cruz Ribeiro",
    "cargo": "Serralheiro",
    "origem": "LT50/JS50",
    "empresa": "LT Decorações",
    "mes": "Fevereiro",
    "salario_base": 3000.81,
    "insalubridade": 648.4,
    "hora_extra": 0,
    "inss": 327.21,
    "fgts": 291.87,
    "transporte": 0,
    "adiantamento": 0,
    "total": 3322.0
  }
];